package dev.comma.agent.apidoc;

public record ApiDocDebugField(
        String name,
        String jsonType,
        boolean required,
        String readyMeaning,
        String needsInputMeaning,
        String usage,
        int displayOrder,
        String category,
        String uiLabel,
        String uiDescription,
        String visibility,
        String renderType,
        boolean copyable,
        String interactionHint,
        String agentAction,
        String targetNode,
        String nodeInputPath,
        String handoffPayloadKey,
        boolean requiredForNode,
        Object fallbackValue,
        String validationRule,
        String missingFieldPolicy,
        String policySeverity,
        boolean retryable,
        String operatorMessage,
        String failureEscalation,
        String escalationCondition,
        String failureEscalationMessage,
        int escalationPriority,
        String escalationCategory,
        String escalationSla,
        String escalationContact,
        String escalationRunbook,
        String source,
        Object readyExampleValue,
        Object needsInputExampleValue) {
}
